base_url         = "https://example.com" # The URL the site will be built for
title            = "Zermo"               # Used in RSS by default
description      = "A description"
default_language = "en"                  # The default language, used in RSS
generate_feed    = true                  # Whether to generate a RSS feed automatically

# feed_filename = "atom.xml" # 'atom.xml' (default if unspecified) and 'rss.xml' are officially supported
# theme = "" # Theme name to use.

compile_sass       = true  # Whether to automatically compile all Sass files in the sass directory
build_search_index = false # Whether to build a search index to be used later on by a JavaScript library

taxonomies = [
    { name = "tags" },
    { name = "categories" },
] # Built in taxonomies of zerm.

[extra] # Put all your custom variables here

# inject extra scripts in the <head> tag
# script = '''
# '''

author          = "You!"  # Author name to be added to posts, if enabled.
show_author     = false   # Show author's name in blog post meta data.
show_categories = true    # Show categories a blog post is marked with in its meta data.
show_tags       = true    # Show tags a blog post is marked with in its meta data.

# one of ["dark_orange", "dark_blue", "dark_red", "dark_green", "dark_pink", "light_lilac", "light_blue"]
theme_color = "light_lilac"

# Custom css to style over the defaults. This is useful when you only have a
# few small tweaks to make rather than a major rehaul to the theme.
# It would be best to make this a proper .sass or .scss file in sass/ rather
# than placing in static/
# custom_css = "custom.css"

# How many menu items to show on desktop. if you set this to 0, only submenu
# button will be visible.
show_menu_items = 6

full_width = false         # set theme to full screen width.
center     = true          # center theme with default width.
favicon    = "favicon.ico" # set a custom favicon. Must be placed in root of static/ directory...
copyright  = "Zermo"       # Copyright notice (name of site owner) if desired.
logo_text  = "Zermo"       # What is displayed in the top left corner of the website. Default is zerm.

# Set a custom preview image for your website when posted as a link.
# Must be placed in root of static/ directory...
# og_preview_img = ""

# Link in logo. Default returns you to $BASE_URL.
# logo_home_link = "/"

main_menu = [
    { url = "/menu_about/", name = "about" },
    { url = "/menu_contact/", name = "contact" },
    { url = "/menu_links/", name = "links" },
] # Menu items to display. You define a url and the name of the menu item.

language_menu = [
    # { url = "/", name = "en" },
    # { url = "/fr", name = "fr" },
    # { url = "/zh", name = "zh" },
] # add more languages here

# Displayed as title of drop-down menu when size of main_menu > show_menu_items.
menu_more = "show more"

read_more = "read more" # Displayed after teaser text for a blog post.

enable_katex = true # Enable math typesetting with KaTeX
# ToC = true # Generate Table of Contents for all articles

# Generate "on repeat" music section on the homepage
# TODO: make this prettier
# FIXME: currently broken
enable_on_repeat = false
on_repeat = [
    { name = "test", video_url = "some_url", image_url = "some_url" },
    { name = "test1", video_url = "some_url", image_url = "some_url" },
]

# Options for disqus
disqus = { enabled = false, short_name = "" }

[markdown]
highlight_code  = true
highlight_theme = "OneHalfDark"
