name        = "zermo"
description = "Léana's fork of light themed zerm"
license     = "MIT"
# homepage    = "https://github.com/ejmg/zerm"
min_version = "0.8.0" # The minimum version of Zola required

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Léana"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
name     = "elias julian marko garcia"
homepage = "https://github.com/ejmg"
repo     = "https://github.com/ejmg"
